### PR TITLE
Shift removal pass

### PR DESCRIPTION
**Pull request by bts**
@cartazio @joelburget

### CODE REVIEW

**Comment by cartazio** [comment]
Why does the bit set rep come up? Why not just do fromIntegral and back
again? Or at you trying to avoid an overflow?

I'll look again in the morning. But it should just be pushing a sum down
into the leaves right? Plus tracking a depth?

I guess I'm overlooking tracking which variables are free relative to a
given depth. Which suggests that we want to do some partial sum of depth
histograms?  I need to reload this accounting into my head!

Either way, awesome

**Comment by bts** [comment]
I'm using the bitset because:
- we need to push down multiple shifts (of different values) simultaneously
- all shifts we've seen so far increase in value as we push them down past each binder
- once we hit a variable, it's bumped once for every shift we're tracking that has a value <= the debruijn index

Though as I write this now, it occurs me to that we actually need something slightly richer for one case where this approach will fail: if we have `shift 0 $ shift 0 $ v1`, we can only set a single bit for the `0` position, whereas we want to bump twice, once for each shift. Here's the failing case, which yields `v2` instead of `v3`:

```haskell
it "bumps multiple times for a duplicate shift value" $
  let term  = shift 0 $ shift 0 $ v1
      term' = v3
  in removeBinderShifts term `shouldBe` term'
```

I'll fix this bug tomorrow.

**Comment by cartazio** [comment]
Cool, I'd like to figure out a visual way to think about this.  There's
definitely a naive quadratic time approach we could do, though it might not
be quadratic as I say that.  There's sort of an implcit water mark / sea
level for a shift. Let's flesh out some ideas tomorrow

**Comment by bts** [comment]
Yeah, exactly -- it needs to be histogram-ish

**Comment by bts** [comment]
Yeah that sounds good. As you mentioned, it will look histogram-y

**Comment by cartazio** [comment]
So let's think it out, I had some ideas this morning :
First let's look at vanilla bound and wha they do
https://hackage.haskell.org/package/bound-1.0.7/docs/src/Bound-Scope.html#fromScope

So perhaps the most naive thing we could do correctly is rebuild the
subtree under any tree shift, and do that recursively in the sub
computations.

But let's now talk about the number of tree shifts that could happen in a
given ast.

Observation 1: no source / elaborator asts will have tree shift by default
, we intend to use this as a means to get implcit sharing and to enable
efficient cse and inlining both, I believe

Observation 2: along any path to a leaf in the ast , there should never be
more tree shift nodes than binder introductions.

Observation 3: an implcit invariant we have is that we can't / should have
double shift in a row or shift then any sort of variable free sub
expression or global only variable  or directly over a single local
variable.  A simpler but still sound rule would be to think of variables
and tree shifts as being "negative " vs other constructors as being
positive, any double negative pair should always get compacted away / not
be allowed.  Or something of that sort.

Maybe just naively repeatedly re walking / building the subtree for each
shift push wouldn't be that bad? Or maybe there's a simple solution that's
more linear time and not terribly complex and has good constants?

This is my morning thoughts, so I may be missing something obvious. I do
like the idea of the partial sums histogram as a way of talking about the
deferred shifts semantically. But I'm not sure if there's enough
performance to pay for doign that correctly at the moment?

Thoughts?

**Comment by bts** [comment]
I think we can keep things simpler than rebuilding any trees. Consider we keep an approach similar to what I'm doing now, but use a "sequence" (_not_ `Data.Sequence`) of ints instead of bools. For this sequence, we could either use a list or, if you can help me find an impl in Haskell, a mutable vector with amortized constant grow (it seems that `Data.Vector.Unboxed.Mutable`, via `Data.Vector.Generic.Mutable` offers log grow?).

If we use `[Int]`, we can view `(0:)` as incrementing all binder shifts as we enter a new scope, we can get the following asymptotics:

* encounter shift: O(2*|shift|)
* enter scope: O(1)
* encounter variable: O(deBruijnIndex)

A growable mutable vector could give us:

* encounter shift: amortized O(1) [we possibly grow; then do O(1) access]
* enter scope: amortized O(1) [we grow]
* encounter variable: O(deBruijnIndex)

**Comment by cartazio** [comment]
There's some interesting trade offs afoot here.  Let's see if we can work
out something that has logs instead of linears perhaps

**Comment by bts** [comment]
going to use `[Int]` because it has better sharing

**Comment by bts** [comment]
I think this is ready to go in now -- let me know if you guys have any feedback.

**Comment by cartazio** [comment]
lets add this for now, I think binders might change up soon, but this is useful for now

It important to note that this version of Shift is a "one level shift, starting at level >=C in the current scope", as I definitely was confused about the semantics

**Pull request merged**
